# Generated by Django 3.1.3 on 2021-01-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('county', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Uasin-gishu', 'Uasin-gishu'), ('Ravine', 'Ravine'), ('Kisumu', 'Kisumu'), ('Wajir', 'Wajir'), ('Kajiado', 'Kajiado'), ('Kiambu', 'Kiambu'), ('Elgeyo-marakwet', 'Elgeyo-marakwet'), ('Nandi', 'Nandi'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Thika', 'Thika'), ('Embakasi', 'Embakasi')], max_length=20)),
                ('idNumber', models.IntegerField()),
                ('phoneNumber', models.IntegerField()),
            ],
        ),
    ]
