# Generated by Django 3.1.3 on 2021-01-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinary',
            name='county',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Uasin-gishu', 'Uasin-gishu'), ('Ravine', 'Ravine'), ('Kisumu', 'Kisumu'), ('Wajir', 'Wajir'), ('Kajiado', 'Kajiado'), ('Kiambu', 'Kiambu'), ('Elgeyo-marakwet', 'Elgeyo-marakwet'), ('Nandi', 'Nandi'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Thika', 'Thika'), ('Embakasi', 'Embakasi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
