# Generated by Django 3.1.3 on 2021-01-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0002_auto_20210117_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinary',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='idNumber',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='phoneNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
